schema: ./schema.graphql
documents: ''
extensions:
  endpoints:
    master:
      url: https://api-eu-central-1.graphcms.com/v2/ckk2iqjmrrv0e01xs8shscgad/master
      introspect: true
      headers:
        - user-agent: JS GraphQL
        - Authorization:  "Bearer "
  codegen:
    generates:
      ./generated-backend.ts:
        plugins:
          - typescript
          - typescript-resolvers
      ./generated-frontend.ts:
        plugins:
          - typescript
          - typescript-resolvers
  diff:
    baseSchema: your-base-schema-here
